// Nieuwe account- en beheerteksten. Ze staan tijdelijk apart zodat de nieuwe
// schermen volledig tweetalig zijn terwijl de centrale woordenlijst parallel
// wordt uitgebreid. Darija wordt bewust in Latijnse letters en LTR geschreven.
const copy = {
  nl: {
    publicTitle: 'Leer Nederlands. Stap voor stap.',
    publicSubtitle: 'Korte, praktische lessen voor het dagelijkse leven in Gent.',
    publicPrivacy: 'Je voortgang is privé. Alleen jij en de beheerder kunnen je leergegevens bekijken.',
    publicBadge: 'Praktisch Nederlands voor elke dag',
    brandName: 'Nederlands leren',
    brandPlace: 'in Gent',
    helpBoth: 'Hulp · Mosa3ada',
    location: 'Gent · België',
    signIn: 'Aanmelden',
    register: 'Account aanvragen',
    signOut: 'Afmelden',
    username: 'Gebruikersnaam',
    displayName: 'Naam (optioneel)',
    password: 'Wachtwoord',
    currentPassword: 'Huidig wachtwoord',
    newPassword: 'Nieuw wachtwoord',
    confirmPassword: 'Herhaal wachtwoord',
    showPassword: 'Toon wachtwoord',
    hidePassword: 'Verberg wachtwoord',
    backHome: 'Terug naar start',
    loginIntro: 'Vul je gebruikersnaam en wachtwoord in.',
    forgotPassword: 'Wachtwoord vergeten?',
    resetIntro: 'Vraag de beheerder om een tijdelijke code en vul ze hier in.',
    temporaryCode: 'Tijdelijke resetcode',
    setNewPassword: 'Nieuw wachtwoord instellen',
    resetDone: 'Je nieuwe wachtwoord is ingesteld. Je kunt nu aanmelden.',
    registerIntro: 'Kies zelf een gebruikersnaam en wachtwoord. De beheerder keurt je aanvraag eerst goed.',
    accountRequested: 'Je aanvraag is verzonden',
    accountRequestedHint: 'Je krijgt toegang zodra de beheerder je account heeft goedgekeurd.',
    pendingTitle: 'Je account wacht op goedkeuring',
    pendingBody: 'De beheerder bekijkt je aanvraag. Probeer later opnieuw of vernieuw de status.',
    rejectedTitle: 'Je aanvraag is niet goedgekeurd',
    rejectedBody: 'Vraag de beheerder om hulp als je denkt dat dit een vergissing is.',
    suspendedTitle: 'Je account is tijdelijk geblokkeerd',
    suspendedBody: 'Neem contact op met de beheerder om opnieuw toegang te krijgen.',
    refresh: 'Status vernieuwen',
    account: 'Mijn account',
    learning: 'Leren',
    admin: 'Beheer',
    changePassword: 'Wachtwoord wijzigen',
    passwordChanged: 'Je wachtwoord is gewijzigd. Andere sessies zijn afgemeld.',
    passwordRules: 'Gebruik minstens 10 tekens.',
    passwordMismatch: 'De twee wachtwoorden zijn niet hetzelfde.',
    usernameRules: 'Gebruik 3–32 letters, cijfers, een streepje of liggend streepje.',
    required: 'Vul alle verplichte velden in.',
    loading: 'Even laden…',
    retry: 'Opnieuw proberen',
    serverUnavailable: 'De beveiligde server is niet bereikbaar. Probeer het straks opnieuw.',
    adminTitle: 'Beheerdersdashboard',
    adminSubtitle: 'Accounts, activiteit en opdrachten',
    users: 'Gebruikers',
    assignments: 'Opdrachten',
    all: 'Alle',
    pending: 'In afwachting',
    active: 'Actief',
    rejected: 'Geweigerd',
    suspended: 'Geblokkeerd',
    approve: 'Goedkeuren',
    reject: 'Weigeren',
    block: 'Blokkeren',
    unblock: 'Deblokkeren',
    resetPassword: 'Tijdelijke resetcode',
    resetCode: 'Eenmalige resetcode',
    resetWarning: 'De code wordt maar één keer getoond. Deel hem veilig met de gebruiker.',
    copyCode: 'Code kopiëren',
    copied: 'Gekopieerd',
    expires: 'Geldig tot',
    noUsers: 'Geen gebruikers in deze lijst.',
    registered: 'Geregistreerd',
    lastActive: 'Laatst actief',
    online: 'Online',
    offline: 'Offline',
    openAssignments: 'openstaande opdrachten',
    recentAttempts: 'Recente pogingen',
    noAttempts: 'Nog geen pogingen opgeslagen.',
    showDetails: 'Details tonen',
    hideDetails: 'Details verbergen',
    todayMinutes: 'Vandaag',
    weekMinutes: '7 dagen',
    monthMinutes: '30 dagen',
    totalMinutes: 'Totaal',
    estimatedTime: 'Geschatte actieve leertijd',
    selectUser: 'Kies een gebruiker',
    assignmentTitle: 'Titel van de opdracht',
    assignmentTitleNl: 'Titel in het Nederlands',
    assignmentTitleDar: 'Titel in Darija (Latijnse letters)',
    assignmentInstructions: 'Korte uitleg (optioneel)',
    assignmentInstructionsNl: 'Uitleg in het Nederlands (optioneel)',
    assignmentInstructionsDar: 'Uitleg in Darija-Latijn (optioneel)',
    lessonId: 'Les of oefening',
    assignmentType: 'Type',
    extra: 'Extra',
    mandatory: 'Verplicht',
    dueDate: 'Deadline (optioneel)',
    createAssignment: 'Opdracht toevoegen',
    noAssignments: 'Er zijn nog geen opdrachten.',
    assignmentCreated: 'De opdracht is toegewezen.',
    open: 'Open',
    completed: 'Voltooid',
    cancelled: 'Geannuleerd',
    cancel: 'Annuleren',
    markCompleted: 'Handmatig voltooien',
    confirmAction: 'Weet je het zeker?',
    close: 'Sluiten',
    studentAssignments: 'Jouw opdrachten',
    mandatoryFirst: 'Rond eerst je verplichte opdracht af om verder te leren.',
    goToAssignment: 'Open opdracht',
    noLessonLink: 'Deze opdracht heeft geen rechtstreekse leskoppeling.',
  },
  dar: {
    publicTitle: 'T3ellem Nederlands, chwya b chwya.',
    publicSubtitle: 'Dorous qsar w 3amaliyin bach tsta3mel Nederlands f l7ayat dyal kol nhar f Gent.',
    publicPrivacy: 'Taqaddom dyalek privé. Ghir nta w l-admin li yqedrou ychoufou ma3loumat ta3allom dyalek.',
    publicBadge: 'Nederlands 3amali l-kol nhar',
    brandName: 'T3ellem Nederlands',
    brandPlace: 'f Gent',
    helpBoth: 'Mosa3ada · Hulp',
    location: 'Gent · Belgique',
    signIn: 'Dkhol',
    register: 'Tleb compte',
    signOut: 'Khroj',
    username: 'Smiyet l-mosta3mil',
    displayName: 'Smiytek (ikhtiyari)',
    password: 'Mot de passe',
    currentPassword: 'Mot de passe l-qdim',
    newPassword: 'Mot de passe jdid',
    confirmPassword: '3awed mot de passe',
    showPassword: 'Werri mot de passe',
    hidePassword: 'Khbbi mot de passe',
    backHome: 'Rje3 l-bidaya',
    loginIntro: 'Dkhel smiyet l-mosta3mil w mot de passe dyalek.',
    forgotPassword: 'Nsiti mot de passe?',
    resetIntro: 'Tleb code mo2aqqat mn l-admin w dkhlo hna.',
    temporaryCode: 'Code mo2aqqat',
    setNewPassword: 'Dir mot de passe jdid',
    resetDone: 'Mot de passe jdid t7ett. Daba tqder tdokhol.',
    registerIntro: 'Khtar smiyet l-mosta3mil w mot de passe. L-admin khaso yqbel talab dyalek qbel ma tdokhol.',
    accountRequested: 'Talab dyalek tsift',
    accountRequestedHint: 'Ghadi tqder tdokhol mlli l-admin yqbel compte dyalek.',
    pendingTitle: 'Compte dyalek mazal kaytsenna l-mowafaqa',
    pendingBody: 'L-admin ghadi ychouf talab dyalek. 3awed jereb mn be3d wela jedded status.',
    rejectedTitle: 'Talab dyalek ma tqbelch',
    rejectedBody: 'Hder m3a l-admin ila ban lik kayna chi ghalta.',
    suspendedTitle: 'Compte dyalek mbloké mo2aqqatan',
    suspendedBody: 'Hder m3a l-admin bach yrje3 y7ell lik compte.',
    refresh: 'Jedded status',
    account: 'Compte dyali',
    learning: 'T3ellem',
    admin: 'L-idara',
    changePassword: 'Beddel mot de passe',
    passwordChanged: 'Mot de passe tbeddel. Sessions l-khrin tseddo.',
    passwordRules: 'St3mel 10 dyal l-7orouf 3la l-aqall.',
    passwordMismatch: 'Joj mots de passe machi kif kif.',
    usernameRules: 'St3mel mn 3 7tta 32: 7orouf, arqam, tiret wela underscore.',
    required: '3emmer ga3 l-khanat darouriyin.',
    loading: 'Tsena chwya…',
    retry: '3awed jereb',
    serverUnavailable: 'Serveur l-ma7mi ma kayjawbch daba. 3awed jereb mn be3d.',
    adminTitle: 'Tableau dyal l-admin',
    adminSubtitle: 'Comptes, lwaqt li t9ra w devoirat',
    users: 'L-mosta3milin',
    assignments: 'Devoirat',
    all: 'Kamlin',
    pending: 'Kaytsennaw',
    active: 'Khddamin',
    rejected: 'Merfoudin',
    suspended: 'Mblokyin',
    approve: 'Qbel',
    reject: 'Rfed',
    block: 'Bloki',
    unblock: '7ell l-compte',
    resetPassword: 'Code mo2aqqat',
    resetCode: 'Code kaytkhdem ghir merra',
    resetWarning: 'Had code kayban ghir merra. 3tih l-mosta3mil b tariqa amna.',
    copyCode: 'Copier l-code',
    copied: 'Tcoppa',
    expires: 'Sal7 7tta',
    noUsers: 'Ma kayn 7tta mosta3mil f had lista.',
    registered: 'Tsejjel',
    lastActive: 'Akher mara kan actif',
    online: 'Online',
    offline: 'Offline',
    openAssignments: 'devoirat mazel ma tkemmlouch',
    recentAttempts: 'Akher mo7awalat',
    noAttempts: 'Mazal ma kayna 7tta mo7awala.',
    showDetails: 'Werri tafasil',
    hideDetails: 'Khbbi tafasil',
    todayMinutes: 'Lyoum',
    weekMinutes: '7 iyam',
    monthMinutes: '30 nhar',
    totalMinutes: 'Lmajmou3',
    estimatedTime: 'Lwaqt taqribi dyal ta3allom',
    selectUser: 'Khtar mosta3mil',
    assignmentTitle: 'Smiyet devoir',
    assignmentTitleNl: 'Smiyet devoir b Nederlands',
    assignmentTitleDar: 'Smiyet devoir b Darija (7orouf Latiniya)',
    assignmentInstructions: 'Chre7 b ikhtisar (ikhtiyari)',
    assignmentInstructionsNl: 'Chre7 b Nederlands (ikhtiyari)',
    assignmentInstructionsDar: 'Chre7 b Darija-Latijn (ikhtiyari)',
    lessonId: 'Ders wela tamrin',
    assignmentType: 'Naw3',
    extra: 'Ziyadi',
    mandatory: 'Darouri',
    dueDate: 'Akher ajal (ikhtiyari)',
    createAssignment: 'Zid devoir',
    noAssignments: 'Mazal ma kayn 7tta devoir.',
    assignmentCreated: 'Devoir tzad l-mosta3mil.',
    open: 'Ma7loul',
    completed: 'Tkemmel',
    cancelled: 'Tlegha',
    cancel: 'Lghi',
    markCompleted: '3ellem belli tkemmel',
    confirmAction: 'Mte2kked?',
    close: 'Sedd',
    studentAssignments: 'Devoirat dyalek',
    mandatoryFirst: 'Kmmel devoir darouri qbel ma tkemmel ta3allom.',
    goToAssignment: '7ell devoir',
    noLessonLink: 'Had devoir ma merboutch directement b chi ders.',
  },
}

export function uiCopy(lang, key) {
  return copy[lang]?.[key] ?? copy.nl[key] ?? key
}
