// Nieuwe account- en beheerteksten. Ze staan tijdelijk apart zodat de nieuwe
// schermen volledig tweetalig zijn terwijl de centrale woordenlijst parallel
// wordt uitgebreid. Darija wordt bewust in Latijnse letters en LTR geschreven.
const copy = {
  nl: {
    publicTitle: 'Leer Nederlands. Stap voor stap.',
    publicSubtitle: 'Korte, praktische lessen voor het dagelijkse leven in Gent.',
    publicPrivacy: 'Je voortgang is privé. Alleen jij en de beheerder kunnen je leergegevens bekijken.',
    publicBadge: 'Praktisch Nederlands voor elke dag',
    brandName: 'Nederlands leren',
    brandPlace: 'in Gent',
    helpBoth: 'Hulp · Mosa3ada',
    location: 'Gent · België',
    signIn: 'Aanmelden',
    register: 'Account aanvragen',
    signOut: 'Afmelden',
    username: 'Gebruikersnaam',
    displayName: 'Naam (optioneel)',
    password: 'Wachtwoord',
    currentPassword: 'Huidig wachtwoord',
    newPassword: 'Nieuw wachtwoord',
    confirmPassword: 'Herhaal wachtwoord',
    showPassword: 'Toon wachtwoord',
    hidePassword: 'Verberg wachtwoord',
    backHome: 'Terug naar start',
    loginIntro: 'Vul je gebruikersnaam en wachtwoord in.',
    forgotPassword: 'Wachtwoord vergeten?',
    resetIntro: 'Vraag de beheerder om een tijdelijke code en vul ze hier in.',
    temporaryCode: 'Tijdelijke resetcode',
    setNewPassword: 'Nieuw wachtwoord instellen',
    resetDone: 'Je nieuwe wachtwoord is ingesteld. Je kunt nu aanmelden.',
    registerIntro: 'Kies zelf een gebruikersnaam en wachtwoord. De beheerder keurt je aanvraag eerst goed.',
    accountRequested: 'Je aanvraag is verzonden',
    accountRequestedHint: 'Je krijgt toegang zodra de beheerder je account heeft goedgekeurd.',
    pendingTitle: 'Je account wacht op goedkeuring',
    pendingBody: 'De beheerder bekijkt je aanvraag. Probeer later opnieuw of vernieuw de status.',
    rejectedTitle: 'Je aanvraag is niet goedgekeurd',
    rejectedBody: 'Vraag de beheerder om hulp als je denkt dat dit een vergissing is.',
    suspendedTitle: 'Je account is tijdelijk geblokkeerd',
    suspendedBody: 'Neem contact op met de beheerder om opnieuw toegang te krijgen.',
    refresh: 'Status vernieuwen',
    account: 'Mijn account',
    learning: 'Leren',
    admin: 'Beheer',
    changePassword: 'Wachtwoord wijzigen',
    passwordChanged: 'Je wachtwoord is gewijzigd. Andere sessies zijn afgemeld.',
    passwordRules: 'Gebruik minstens 10 tekens.',
    passwordMismatch: 'De twee wachtwoorden zijn niet hetzelfde.',
    usernameRules: 'Gebruik 3–32 letters, cijfers, een streepje of liggend streepje.',
    required: 'Vul alle verplichte velden in.',
    loading: 'Even laden…',
    retry: 'Opnieuw proberen',
    serverUnavailable: 'De beveiligde server is niet bereikbaar. Probeer het straks opnieuw.',
    adminTitle: 'Beheerdersdashboard',
    adminSubtitle: 'Accounts, activiteit en opdrachten',
    users: 'Gebruikers',
    assignments: 'Opdrachten',
    pronunciationReviews: 'Uitspraak',
    aiFeedbackTab: 'AI-uitleg',
    referenceAudioTab: 'Lesaudio',
    referenceAudioTitle: 'Opnamestudio voor de lessen',
    referenceAudioIntro: 'Neem ieder woord of iedere korte zin één keer rustig en duidelijk op. Na opslaan gebruikt de juiste les deze opname automatisch.',
    referenceAudioRecorded: 'opgenomen',
    referenceAudioMissing: 'nog te doen',
    referenceAudioComplete: 'Klaar voor gebruik',
    referenceAudioCategory: 'Reeks',
    recordingGuideTitle: 'Zo maak je een goede opname',
    recordingGuide: 'Ga in een stille kamer zitten. Houd je telefoon 15–20 cm van je mond. Tik op opnemen, wacht één tel, spreek natuurlijk, wacht nog één tel en tik dan op stoppen.',
    promptToRecord: 'Lees exact dit voor',
    startRecording: 'Start opname',
    stopRecording: 'Stop opname',
    recording: 'Opname bezig',
    recordingStarted: 'De opname is gestart.',
    recordingReady: 'De opname is gestopt en klaar om te beluisteren.',
    listenBeforeSave: 'Beluister eerst je nieuwe opname',
    approveAndSave: 'Goedkeuren en opslaan',
    savedAndLinked: 'Opgeslagen en automatisch aan de les gekoppeld.',
    replaceRecording: 'Nieuwe versie opnemen',
    nextMissing: 'Volgende ontbrekende',
    previousPrompt: 'Vorige',
    nextPrompt: 'Volgende',
    allRecorded: 'Alle verplichte opnames zijn klaar.',
    audioTooShort: 'De opname is leeg of te kort. Probeer opnieuw.',
    audioMustListen: 'Beluister de hele opname voordat je ze opslaat.',
    existingRecording: 'Huidige opname in de les',
    preferDarijaSpeaker: 'Laat de vijf Darija-zinnen bij voorkeur door een natuurlijke Darija-spreker inspreken.',
    recordingProgress: 'Totale voortgang',
    uploading: 'Bezig met opslaan…',
    discardRecording: 'Nieuwe opname wissen',
    discardRecordingConfirm: 'Deze nieuwe opname is nog niet opgeslagen. Wil je ze wissen en doorgaan?',
    recordingConsent: 'Ik heb toestemming om deze stem blijvend als lesaudio te gebruiken. Een verwijderde of vervangen opname kan nog maximaal 7 dagen in Cloudflare-herstelback-ups staan.',
    deleteRecording: 'Opgeslagen opname verwijderen',
    deleteRecordingConfirm: 'Wil je deze opgeslagen lesopname verwijderen? De les gebruikt daarna tijdelijk de computerstem.',
    recordingDeleted: 'De opname is verwijderd. De les gebruikt voorlopig de computerstem.',
    recordingOutdated: 'De lesprompt is veranderd. Maak een nieuwe opname voordat deze audio opnieuw gebruikt wordt.',
    audioPlaybackError: 'Deze opname kon niet worden afgespeeld. Neem ze opnieuw op of probeer een andere browser.',
    orphanedAudioTitle: 'Oude audio zonder leskoppeling',
    orphanedAudioIntro: 'Deze opname hoort niet meer bij een bestaande prompt en kan veilig worden verwijderd.',
    micNotSupported: 'Opnemen wordt niet ondersteund in deze browser.',
    micNoPermission: 'Geef de browser toestemming om de microfoon te gebruiken.',
    micNoStart: 'De microfoon kon niet worden gestart.',
    aiFeedbackTitle: 'Gemelde AI-uitleg',
    noAiFeedback: 'Er is geen gemelde AI-uitleg om na te kijken.',
    aiReports: 'meldingen',
    aiLessonItem: 'Les en woord',
    aiMarkChecked: 'Nagekeken en correct',
    aiRegenerate: 'Nieuwe uitleg laten maken',
    aiFeedbackPrivacy: 'Je ziet alleen de gemaakte uitleg; nooit audio of een spraaktranscript.',
    noPronunciationReviews: 'Er staan geen opnames klaar voor beoordeling.',
    expectedSpeech: 'Verwacht',
    recognizedSpeech: 'Automatisch gehoord',
    listenRecording: 'Beluister de opname',
    approvePronunciation: 'Goed uitgesproken',
    requestRetry: 'Opnieuw laten oefenen',
    reviewPrivacyAdmin: 'Audio wordt na je beoordeling onmiddellijk verwijderd.',
    all: 'Alle',
    pending: 'In afwachting',
    active: 'Actief',
    rejected: 'Geweigerd',
    suspended: 'Geblokkeerd',
    approve: 'Goedkeuren',
    reject: 'Weigeren',
    block: 'Blokkeren',
    unblock: 'Deblokkeren',
    resetPassword: 'Tijdelijke resetcode',
    resetCode: 'Eenmalige resetcode',
    resetWarning: 'De code wordt maar één keer getoond. Deel hem veilig met de gebruiker.',
    copyCode: 'Code kopiëren',
    copied: 'Gekopieerd',
    expires: 'Geldig tot',
    noUsers: 'Geen gebruikers in deze lijst.',
    registered: 'Geregistreerd',
    lastActive: 'Laatst actief',
    online: 'Online',
    offline: 'Offline',
    openAssignments: 'openstaande opdrachten',
    recentAttempts: 'Recente pogingen',
    noAttempts: 'Nog geen pogingen opgeslagen.',
    showDetails: 'Details tonen',
    hideDetails: 'Details verbergen',
    todayMinutes: 'Vandaag',
    weekMinutes: '7 dagen',
    monthMinutes: '30 dagen',
    totalMinutes: 'Totaal',
    estimatedTime: 'Geschatte actieve leertijd',
    selectUser: 'Kies een gebruiker',
    assignmentTitle: 'Titel van de opdracht',
    assignmentTitleNl: 'Titel in het Nederlands',
    assignmentTitleDar: 'Titel in Darija (Latijnse letters)',
    assignmentInstructions: 'Korte uitleg (optioneel)',
    assignmentInstructionsNl: 'Uitleg in het Nederlands (optioneel)',
    assignmentInstructionsDar: 'Uitleg in Darija-Latijn (optioneel)',
    lessonId: 'Les of oefening',
    assignmentType: 'Type',
    extra: 'Extra',
    mandatory: 'Verplicht',
    dueDate: 'Deadline (optioneel)',
    createAssignment: 'Opdracht toevoegen',
    noAssignments: 'Er zijn nog geen opdrachten.',
    assignmentCreated: 'De opdracht is toegewezen.',
    open: 'Open',
    completed: 'Voltooid',
    cancelled: 'Geannuleerd',
    cancel: 'Annuleren',
    markCompleted: 'Handmatig voltooien',
    confirmAction: 'Weet je het zeker?',
    close: 'Sluiten',
    studentAssignments: 'Jouw opdrachten',
    mandatoryFirst: 'Rond eerst je verplichte opdracht af om verder te leren.',
    goToAssignment: 'Open opdracht',
    noLessonLink: 'Deze opdracht heeft geen rechtstreekse leskoppeling.',
  },
  dar: {
    publicTitle: 'T3ellem Nederlands, chwya b chwya.',
    publicSubtitle: 'Dorous qsar w 3amaliyin bach tsta3mel Nederlands f l7ayat dyal kol nhar f Gent.',
    publicPrivacy: 'Taqaddom dyalek privé. Ghir nta w l-admin li yqedrou ychoufou ma3loumat ta3allom dyalek.',
    publicBadge: 'Nederlands 3amali l-kol nhar',
    brandName: 'T3ellem Nederlands',
    brandPlace: 'f Gent',
    helpBoth: 'Mosa3ada · Hulp',
    location: 'Gent · Belgique',
    signIn: 'Dkhol',
    register: 'Tleb compte',
    signOut: 'Khroj',
    username: 'Smiyet l-mosta3mil',
    displayName: 'Smiytek (ikhtiyari)',
    password: 'Mot de passe',
    currentPassword: 'Mot de passe l-qdim',
    newPassword: 'Mot de passe jdid',
    confirmPassword: '3awed mot de passe',
    showPassword: 'Werri mot de passe',
    hidePassword: 'Khbbi mot de passe',
    backHome: 'Rje3 l-bidaya',
    loginIntro: 'Dkhel smiyet l-mosta3mil w mot de passe dyalek.',
    forgotPassword: 'Nsiti mot de passe?',
    resetIntro: 'Tleb code mo2aqqat mn l-admin w dkhlo hna.',
    temporaryCode: 'Code mo2aqqat',
    setNewPassword: 'Dir mot de passe jdid',
    resetDone: 'Mot de passe jdid t7ett. Daba tqder tdokhol.',
    registerIntro: 'Khtar smiyet l-mosta3mil w mot de passe. L-admin khaso yqbel talab dyalek qbel ma tdokhol.',
    accountRequested: 'Talab dyalek tsift',
    accountRequestedHint: 'Ghadi tqder tdokhol mlli l-admin yqbel compte dyalek.',
    pendingTitle: 'Compte dyalek mazal kaytsenna l-mowafaqa',
    pendingBody: 'L-admin ghadi ychouf talab dyalek. 3awed jereb mn be3d wela jedded status.',
    rejectedTitle: 'Talab dyalek ma tqbelch',
    rejectedBody: 'Hder m3a l-admin ila ban lik kayna chi ghalta.',
    suspendedTitle: 'Compte dyalek mbloké mo2aqqatan',
    suspendedBody: 'Hder m3a l-admin bach yrje3 y7ell lik compte.',
    refresh: 'Jedded status',
    account: 'Compte dyali',
    learning: 'T3ellem',
    admin: 'L-idara',
    changePassword: 'Beddel mot de passe',
    passwordChanged: 'Mot de passe tbeddel. Sessions l-khrin tseddo.',
    passwordRules: 'St3mel 10 dyal l-7orouf 3la l-aqall.',
    passwordMismatch: 'Joj mots de passe machi kif kif.',
    usernameRules: 'St3mel mn 3 7tta 32: 7orouf, arqam, tiret wela underscore.',
    required: '3emmer ga3 l-khanat darouriyin.',
    loading: 'Tsena chwya…',
    retry: '3awed jereb',
    serverUnavailable: 'Serveur l-ma7mi ma kayjawbch daba. 3awed jereb mn be3d.',
    adminTitle: 'Tableau dyal l-admin',
    adminSubtitle: 'Comptes, lwaqt li t9ra w devoirat',
    users: 'L-mosta3milin',
    assignments: 'Devoirat',
    pronunciationReviews: 'Nno9',
    aiFeedbackTab: 'Char7 AI',
    referenceAudioTab: 'Sawt d-dorous',
    referenceAudioTitle: 'Studio dyal tssjilat d-dorous',
    referenceAudioIntro: 'Sejjel kol kelma wela jomla qsira b chwya w b wodo7. Mlli t7fedha, d-ders s7i7 kayst3melha b rassha.',
    referenceAudioRecorded: 'tsejjlo',
    referenceAudioMissing: 'mazal khas',
    referenceAudioComplete: 'Wajed bach yetst3mel',
    referenceAudioCategory: 'Lmajmou3a',
    recordingGuideTitle: 'Kifach tsawb tssjil mzyan',
    recordingGuide: 'Glas f bit hadya. Khlli téléphone bin 15 w 20 cm mn femmek. Dghat 3la tssjil, tsena wa7ed chwya, hder tabi3i, tsena wa7ed chwya w dghat 3la stop.',
    promptToRecord: 'Qra hadchi bddabt',
    startRecording: 'Bda tssjil',
    stopRecording: 'Wqef tssjil',
    recording: 'Tssjil khddam',
    recordingStarted: 'Tssjil bda.',
    recordingReady: 'Tssjil wqef w wajed bach tsm3o.',
    listenBeforeSave: 'Sme3 tssjil jdid luwel',
    approveAndSave: 'Qbel w 7fed',
    savedAndLinked: 'T7fed w t-rbet b rassha b d-ders.',
    replaceRecording: 'Sejjel version jdida',
    nextMissing: 'Li baqi men be3d',
    previousPrompt: 'Li qbel',
    nextPrompt: 'Li men be3d',
    allRecorded: 'Ga3 tssjilat darouriyin wajdin.',
    audioTooShort: 'Tssjil khawi wela qsir bzaf. 3awed jereb.',
    audioMustListen: 'Sme3 tssjil kamel qbel ma t7efdo.',
    existingRecording: 'Tssjil li kayn daba f d-ders',
    preferDarijaSpeaker: 'Lkhamsa d jomal b Darija, khlli chi wa7ed kayhder Darija tabi3iya ysejjelhom.',
    recordingProgress: 'Taqaddom kamel',
    uploading: 'Kayt7fed…',
    discardRecording: 'Mse7 tssjil jdid',
    discardRecordingConfirm: 'Had tssjil jdid mazal ma t7fedch. Bghiti tmse7o w tkemmel?',
    recordingConsent: '3ndi l-idn bach nst3mel had s-sout f d-dorous. Tssjil li tmse7 wela tbeddel y9der yb9a 7tta 7 iyam f sauvegarde dyal Cloudflare.',
    deleteRecording: 'Mse7 tssjil li t7fed',
    deleteRecordingConfirm: 'Bghiti tmse7 had tssjil dyal d-ders? D-ders ghadi yst3mel sout ordinateur mo2aqqatan.',
    recordingDeleted: 'Tssjil tmse7. D-ders kayst3mel sout ordinateur daba.',
    recordingOutdated: 'Nass dyal d-ders tbeddel. Sejjel version jdida qbel ma yetst3mel had s-sout.',
    audioPlaybackError: 'Had tssjil ma tkhdemch. 3awed sejjel wela jereb navigateur akhor.',
    orphanedAudioTitle: 'Tssjilat 9damin bla ders',
    orphanedAudioIntro: 'Had tssjil ma b9ach merbout b chi prompt. Tqder tmse7o b aman.',
    micNotSupported: 'Had navigateur ma kayda3amch tssjil.',
    micNoPermission: '3ti l-idn l navigateur bach yst3mel microphone.',
    micNoStart: 'Microphone ma bghach ybda.',
    aiFeedbackTitle: 'Char7 AI li ttsift l-mora9aba',
    noAiFeedback: 'Ma kayn 7tta char7 AI kaytsenna l-mora9aba.',
    aiReports: 'tabli8at',
    aiLessonItem: 'Dars w kelma',
    aiMarkChecked: 'Tchaf w s7i7',
    aiRegenerate: 'Sawb char7 jdid',
    aiFeedbackPrivacy: 'Katban lik ghir char7; 3mer ma kayban audio wela transcript dyal sawt.',
    noPronunciationReviews: 'Ma kayn 7tta tasjeel kaytsenna l-mora9aba.',
    expectedSpeech: 'Lkelma lmntloba',
    recognizedSpeech: 'Ach sme3at l-app',
    listenRecording: 'Sme3 tasjeel',
    approvePronunciation: 'Nno9 mzyan',
    requestRetry: 'Khass y3awed yetmerren',
    reviewPrivacyAdmin: 'Audio kaytmsa7 direct mlli t3ti l7okm dyalek.',
    all: 'Kamlin',
    pending: 'Kaytsennaw',
    active: 'Khddamin',
    rejected: 'Merfoudin',
    suspended: 'Mblokyin',
    approve: 'Qbel',
    reject: 'Rfed',
    block: 'Bloki',
    unblock: '7ell l-compte',
    resetPassword: 'Code mo2aqqat',
    resetCode: 'Code kaytkhdem ghir merra',
    resetWarning: 'Had code kayban ghir merra. 3tih l-mosta3mil b tariqa amna.',
    copyCode: 'Copier l-code',
    copied: 'Tcoppa',
    expires: 'Sal7 7tta',
    noUsers: 'Ma kayn 7tta mosta3mil f had lista.',
    registered: 'Tsejjel',
    lastActive: 'Akher mara kan actif',
    online: 'Online',
    offline: 'Offline',
    openAssignments: 'devoirat mazel ma tkemmlouch',
    recentAttempts: 'Akher mo7awalat',
    noAttempts: 'Mazal ma kayna 7tta mo7awala.',
    showDetails: 'Werri tafasil',
    hideDetails: 'Khbbi tafasil',
    todayMinutes: 'Lyoum',
    weekMinutes: '7 iyam',
    monthMinutes: '30 nhar',
    totalMinutes: 'Lmajmou3',
    estimatedTime: 'Lwaqt taqribi dyal ta3allom',
    selectUser: 'Khtar mosta3mil',
    assignmentTitle: 'Smiyet devoir',
    assignmentTitleNl: 'Smiyet devoir b Nederlands',
    assignmentTitleDar: 'Smiyet devoir b Darija (7orouf Latiniya)',
    assignmentInstructions: 'Chre7 b ikhtisar (ikhtiyari)',
    assignmentInstructionsNl: 'Chre7 b Nederlands (ikhtiyari)',
    assignmentInstructionsDar: 'Chre7 b Darija-Latijn (ikhtiyari)',
    lessonId: 'Ders wela tamrin',
    assignmentType: 'Naw3',
    extra: 'Ziyadi',
    mandatory: 'Darouri',
    dueDate: 'Akher ajal (ikhtiyari)',
    createAssignment: 'Zid devoir',
    noAssignments: 'Mazal ma kayn 7tta devoir.',
    assignmentCreated: 'Devoir tzad l-mosta3mil.',
    open: 'Ma7loul',
    completed: 'Tkemmel',
    cancelled: 'Tlegha',
    cancel: 'Lghi',
    markCompleted: '3ellem belli tkemmel',
    confirmAction: 'Mte2kked?',
    close: 'Sedd',
    studentAssignments: 'Devoirat dyalek',
    mandatoryFirst: 'Kmmel devoir darouri qbel ma tkemmel ta3allom.',
    goToAssignment: '7ell devoir',
    noLessonLink: 'Had devoir ma merboutch directement b chi ders.',
  },
}

export function uiCopy(lang, key) {
  return copy[lang]?.[key] ?? copy.nl[key] ?? key
}
